CREATE TABLE IF NOT EXISTS app_state (
  chave VARCHAR(100) PRIMARY KEY,
  dados JSONB NOT NULL DEFAULT '[]'::jsonb,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS produtos (
  id BIGSERIAL PRIMARY KEY, chave VARCHAR(180) UNIQUE NOT NULL, nome VARCHAR(180) NOT NULL,
  categoria VARCHAR(80) NOT NULL DEFAULT 'Roupas', preco NUMERIC(10,2) NOT NULL DEFAULT 0,
  preco_antigo NUMERIC(10,2), imagem TEXT, imagens JSONB NOT NULL DEFAULT '[]'::jsonb,
  descricao TEXT, ativo BOOLEAN NOT NULL DEFAULT TRUE, destaque BOOLEAN NOT NULL DEFAULT FALSE,
  promocao BOOLEAN NOT NULL DEFAULT FALSE, criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
